FROM rabbitmq:3.6.5-management
#RUN echo 'NODENAME=rabbit@localhost' > /etc/rabbitmq/rabbitmq-env.conf

#FROM python

#RUN apt-get update && apt-get install -y wget && wget https://raw.githubusercontent.com/rabbitmq/rabbitmq-management/rabbitmq_v3_5_6/bin/rabbitmqadmin -O /tmp/rabbitmqadmin && \ 
	#chmod 777 /tmp/rabbitmqadmin  && \
	#mv /tmp/rabbitmqadmin /usr/bin/rabbitmqadmin
